backend/account/urls.py
from django.urls import path
from .views import *

app_name='account'

urlpatterns = [
    path('login', Login.as_view(), name='login-view'),
    path('info', Info.as_view()),
    path('token', GetToken.as_view())
]

backend/jwtProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('auth/', include('account.urls'), name='account')
]

backend/account/models.py
from django.db import models
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser, PermissionsMixin
)
# Create your models here.

class UserManager(BaseUserManager):    
   
   use_in_migrations = True    
   
   def create_user(self, email, nickname, password):        
       
       if not email:            
           raise ValueError('must have user email')
       if not password:            
           raise ValueError('must have user password')

       user = self.model(            
           email=self.normalize_email(email),
           nickname=nickname              
       )        
       user.set_password(password)        
       user.save(using=self._db)        
       return user

   def create_superuser(self, email, nickname, password):        
   
       user = self.create_user(            
           email = self.normalize_email(email),
           nickname=nickname,                       
           password=password        
       )
       user.is_admin = True
       user.is_superuser = True
       user.save(using=self._db)
       return user 

class Token(models.Model):
    token = models.CharField('토큰', max_length=400, unique=True)
    piece = models.CharField('토큰조각', default='', max_length=100)
    is_active = models.BooleanField(default=True)

    objects = models.Manager()

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField('아이디(이메일)', max_length=255, unique=True)
    nickname = models.CharField('닉네임', max_length=20, unique=True)
    password = models.CharField('비밀번호', max_length=100)
    is_active = models.BooleanField('활동여부', default=True)
    is_admin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nickname']

    def __str__(self) -> str:
        return self.email

    
    @property
    def is_staff(self) -> bool:
        return self.is_admin
    
    objects = UserManager()

backend/account/views.py
from django.contrib.auth.hashers import check_password
from django.http import HttpResponse
from rest_framework.views import APIView
from rest_framework.exceptions import AuthenticationFailed
from django.template import loader
from rest_framework.response import Response
from .models import User
from .tokens import make_token, check_token, get_token
import json


class Login(APIView):
    def get(self, request, *args, **kwargs):
        context = {
            'user': request.user
        }
        template = loader.get_template('login.html')
        return HttpResponse(template.render(context, request))

    def post(self, request, *args, **kwargs):
        try:
            user = User.objects.get(
                email=request.data['email'],
            )
        except User.DoesNotExist:
            return Response('login fail', 401)
        
        if check_password(request.data['password'], user.password) is False:
                return Response('login fail', 401)

        claims = dict(
            nickname = user.nickname
        )
        in_cookie, in_param = make_token(claims=claims)

        res = HttpResponse(json.dumps(dict(
            token = in_param
        )), content_type='application/json')
        res.set_cookie('jwt', in_cookie, httponly=True)

        return res

class GetToken(APIView):
    def get(self, request):
        if 'jwt' in request.COOKIES:
            in_cookie = request.COOKIES['jwt']
            piece = get_token(in_cookie)
            if piece != '':
                return Response(dict(piece=piece), content_type='application/json')
        else:
            raise AuthenticationFailed
        return Response(status=400)

class Info(APIView):
    def post(self, request):
        nickname = ''
        if 'jwt' in request.COOKIES:
            in_cookie = request.COOKIES['jwt']
            if 'jwt' not in request.data:
                raise AuthenticationFailed
            claims = check_token(in_cookie, request.data['jwt'])
            nickname = claims['nickname']
        return Response(data=nickname)

backend/account/templates/base.html
{% load static %}
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- 부트스트랩 추가 (Add Bootstrap) -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.0/css/bootstrap.min.css">
    <title>Site Name</title>

  </head>

  <body>

    <!-- 내비게이션에 login 링크 추가 -->
    <ul class="nav justify-content-end">
        {% if user.is_active %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'account:login-view' %}">{{user.username}}</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{%url 'account:login-view' %}"> Login</a>
        </li>
        {% endif %}
      </ul>

    <!-- 템플릿 확장을 위한 템플릿 태그 - Block -->
    {% block content %}
    {% endblock %}


  </body>
    <!-- JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
  
</html>

backend/account/templates/login.html
{% extends 'base.html' %}

{% block content %}

<div class="jumbotron jumbotronfluid">

<div class="container my-5" >

    <h3 class="my-3">Login</h3>

    <hr>

    {% if form.errors %}
    <p style="color:red;">아이디, 비밀번호가 일치하지 않습니다. 다시 시도해주세요.</p>
    {% endif %}

    {% if not user.is_authenticated %}
        {% if user.is_active %}
            <p> 페이지에 대한 접근 권한이 없습니다. 접근 권한을 가진 계정으로 로그인해주세요.</p>
        {% else %}
            <p>페이지를 보시려면 로그인을 해주세요.</p>
        {% endif %}
    {% endif %}

    <form method="post" action="">

    {% if not user.is_authenticated %}
    <div class="form-group row">
            <label for="staticEmail" class="col-sm-2 col-form-label">ID</label>
            <div class="col-sm-10 mt-1">
              <input type="text", name="email", value="">
            </div>
          </div>
          <div class="form-group row">
            <label for="inputPassword" class="col-sm-2 col-form-label">Password</label>
            <div class="col-sm-10 mt-1">
              <input type="password", name="password", value="">
            </div>
          </div>


    <button class="btn btn-info mt-3" type="submit"> Sign in </button>
    <input type="hidden" name="next" value="{{ next }}">
    </form>
    {% endif %}



</div>

</div>
{% endblock %}